### ISSUE TITLE
Cannot reed property 'copyText' of undefined 

### ISSUE THREAD

**Issue by kevin-bache** [yamill/react-native-pasteboard#2]
Keep getting this error, I think the module is not included properly but I followed readme exactly

**Comment by yamill** [comment]
Can you include your code?

**Comment by kevin-bache** [comment]
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 */
'use strict';

var React = require('react-native');
var PasteBoard = require('react-native-pasteboard');

var {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  AlertIOS,
  TouchableHighlight,
} = React;

var SearchBooks = React.createClass({

  copy() {
    PasteBoard.copyText('Hello world!' , (callback) => {
        AlertIOS.alert('Alert', 'Link copied to clipboard!');
    });
  },

  render: function() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
         <TouchableHighlight onPress={this.copy}>
            <Text style={styles.instructions}>
              Press Cmd+R to reload,{'\n'}
              Cmd+D or shake for dev menu
            </Text>
         </TouchableHighlight>
      </View>
    );
  }
});

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});



module.exports = SearchBooks;

**Comment by kevin-bache** [comment]
https://gist.github.com/kevin-bache/f71e21abbd3df92702a2

**Comment by yamill** [comment]
Just copied and pasted your code and it worked fine.

What error are you receiving?

**Comment by yamill** [comment]
Just copied your code and it worked fine.

What version of react-native are you on?

**Comment by kevin-bache** [comment]
0.9,

I'm not sure I copy/referenced correctly I'm new to React-Native/Xcode. I added the files to the project as per the readme. This is what my project directory looks like in xcode

http://i.imgur.com/K7z8zsF.png

**Comment by kevin-bache** [comment]
Got it working, After adding I had Added folders set to "Create folder references" when it should be set to "Create groups"

**Comment by jhartist** [comment]
You might consider adding this fix to the readme. I'm new to Xcode, and this tripped me up as well. Once I found Kevin's answer though, I was up and running. Thanks!
