### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by satya164** [yamill/react-native-pasteboard#4]
Android support will be great

**Comment by yamill** [comment]
Agreed. Someone can submit a PR for this.

**Comment by lucasfeliciano** [comment]
Is this still maintained ?
If yes I can send the PR

**Comment by yamill** [comment]
Not anymore. RN is now supporting this out-of-the-box for both iOS and Android.

https://github.com/facebook/react-native/blob/46a8f1d8e0f2f779bc09395f02be1d0b71587482/Libraries/Components/Clipboard/Clipboard.js
